
%dw 2.0
output application/java 
---
[{
    ID : 50,
    name : "Aiko",
    number : "sunt",
    description : "ab rem eum architecto nesciunt. elit, aliquid ullamco ea exercitationem magnam consequat. qui dolor dolores tempora cupidatat ",
    origin : "magna",
    destination : "qui",
    startdate : "eiusmod",
    enddate : "aperiam,",
    price : "2.97",
    availablecoupons : "sed",
    reschedulepolicy : "Neque",
    cancellationpolicy : "Lorem",
    destinationlocationdesc : "enim",
    originlocationdesc : "nostrum",
    baggage : 62,
    availableseat : 94,
    carType : "adipisci",
    currency : "autem",
    surgemultiplier : 67,
    rating : 3,
    noofdays : 69,
    images : "59",
    availablecars : 23,
  },
{
    ID : 62,
    name : "Byron",
    number : "iure",
    description : "ad ipsum qui reprehenderit enim ",
    origin : "illo",
    destination : "beatae",
    startdate : "voluptatem",
    enddate : "porro",
    price : "94.65",
    availablecoupons : "totam",
    reschedulepolicy : "ut",
    cancellationpolicy : "eiusmod",
    destinationlocationdesc : "laboris",
    originlocationdesc : "ut",
    baggage : 16,
    availableseat : 82,
    carType : "et",
    currency : "dolore",
    surgemultiplier : 86,
    rating : 83,
    noofdays : 28,
    images : "80",
    availablecars : 87,
  }]
