http:
  host: "![FLqxBD/elYiYXNSe7tQIvg==]"
  port: "![0Yf/Ruv3qsI=]"

database:
  url: "![lnBQ9bPEKQp9B/MUGIjNie89zAAESU5D9zxjAu8krCGXrx4nzlIkWEeF/9C4IkBE25ySdIUtdBg=]"
  driver: "![WvP8fggmtr6BEaWpv9TWeGpfDCCeW9OJ]"
  user: "![T2H0Z28ZUh+cjSIbs/m/rg==]"
  password: "![UTkscEZUMw8A10JJ+5zyRPnMROXh4UHQmco/XHJfn7peCqL1kSyang==]"


amazons3:
  bucket: "![3GFo3rf9iYYAQctRQq6DEQ==]"
  bookingfileName: "![EdQyptIrtv88OoNw/sslxHr3PL42tjKG]"
  accesskey: "![0hWgaFqRXJOYMHNCjNrZcp/qAfubfpWB]"
  securekey: "![ex4W80LgkX+aKpk0LjiZNrinSo62fPjmbiPAY8RHz/GfRdy8YhZwwrGka5bkxfCW]"
